[package]
name = "duplication_testing"
version = "0.1.0"
edition = "2021"

[dependencies]
opencv = "0.94.2"
faiss = { version = "0.12.1", features = ["static"] }
uuid = { version = "1.4", features = ["v4"] }